# Generated by Django 3.2.3 on 2021-05-24 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCaseWebData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('total_cases', models.CharField(max_length=100)),
                ('acive_cases', models.CharField(max_length=100)),
                ('total_deaths', models.CharField(max_length=100)),
                ('recovery_rate', models.CharField(max_length=10)),
                ('pop_infected_per', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Covid Case Data',
                'verbose_name_plural': 'Covid Case Datas',
            },
        ),
    ]
